environment:
  matrix:
    - PYTHON: C:\Python38-x64


install:
  - SET PATH=%PYTHON%;%PYTHON%\Scripts;%PATH%
  - "%PYTHON%\\python.exe --version"
  - "%PYTHON%\\python.exe -m pip install -r requirements.txt"


build_script:
  - pyinstaller --onefile --windowed main.py


artifacts:
  - path: dist\*
